from django.db import models
import uuid
from projects.models import Project

class Sprint(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="sprints")
    duration = models.PositiveIntegerField(null=True, blank=True, help_text="Sprint duration in days")
    start_date = models.DateField(null=True, blank=True, help_text="Sprint start date")
    end_date = models.DateField(null=True, blank=True, help_text="Sprint end date")
    ai = models.BooleanField(default=False, help_text="Was this sprint generated by AI?")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Sprint {self.id} - {self.project.title}"