from django.db import models
import uuid
from projects.models import Project

class Sprint(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="sprints")
    week_number = models.PositiveIntegerField(default=1, help_text="Week number in the project timeline")
    duration = models.PositiveIntegerField(null=True, blank=True, help_text="Sprint duration in days")
    start_date = models.DateField(null=True, blank=True, help_text="Sprint start date")
    end_date = models.DateField(null=True, blank=True, help_text="Sprint end date")
    ai = models.BooleanField(default=False, help_text="Was this sprint generated by AI?")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Week {self.week_number} - {self.project.title}"

class SprintTask(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE, related_name="tasks")
    title = models.CharField(max_length=255, help_text="Task title for this sprint")
    ai = models.BooleanField(default=False, help_text="Was this task generated by AI?")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title