# Generated by Django 5.2.6 on 2025-10-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0002_epic_projectfeature_projectgoal_projectrole_subepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='user_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user_name',
            field=models.CharField(default='Unknown User', max_length=255),
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='ai_api_projectmember',
        ),
    ]
