# Generated by Django 5.2.4 on 2025-10-28 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0005_add_updated_at_to_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('setting_up', 'Setting Up'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('on_hold', 'On Hold')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_invitation', 'Project Invitation'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('mention', 'Mentioned in Chat'), ('deadline_reminder', 'Deadline Reminder'), ('project_update', 'Project Update'), ('project_status_changed', 'Project Status Changed'), ('member_joined', 'Member Joined Project'), ('member_left', 'Member Left Project')], max_length=50),
        ),
    ]
