# Generated by Django 5.2.4 on 2025-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0006_project_status_project_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_invitation', 'Project Invitation'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('mention', 'Mentioned in Chat'), ('deadline_reminder', 'Deadline Reminder'), ('project_update', 'Project Update'), ('project_status_changed', 'Project Status Changed'), ('member_joined', 'Member Joined Project'), ('member_left', 'Member Left Project'), ('task_due_date_set', 'Task Due Date Set')], max_length=50),
        ),
    ]
