# Generated by Django 5.2.4 on 2025-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storytask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storytask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
