# Generated by Django 5.2.4 on 2025-10-29 13:51

from django.db import migrations
from django.utils import timezone


def set_created_at_defaults(apps, schema_editor):
    """Set default created_at values for existing StoryTask records"""
    StoryTask = apps.get_model('ai_api', 'StoryTask')
    now = timezone.now()
    
    # Update all StoryTask records that don't have created_at set
    StoryTask.objects.filter(created_at__isnull=True).update(created_at=now)


def reverse_created_at_defaults(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0008_add_due_date_fields'),
    ]

    operations = [
        migrations.RunPython(set_created_at_defaults, reverse_created_at_defaults),
    ]
