# Generated by Django 5.2.7 on 2025-11-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_two_factor_enabled_user_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
