# Generated by Django 5.2.5 on 2025-09-28 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commit_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commit',
            },
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('very_sad', 'Very Sad')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moodcheckin',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('methodology', models.CharField(choices=[('scrum', 'Scrum'), ('kanban', 'Kanban'), ('agile', 'Agile'), ('waterfall', 'Waterfall')], default='scrum', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='project_management.project')),
            ],
            options={
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sprint_summary', 'Sprint Summary'), ('velocity_report', 'Velocity Report'), ('burndown_chart', 'Burndown Chart'), ('team_performance', 'Team Performance'), ('mood_analytics', 'Mood Analytics')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project_management.sprint')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_management.sprint')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_management.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role_in_team', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_management.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_member',
                'unique_together': {('team', 'user')},
            },
        ),
    ]
