# Generated by Django 5.2.7 on 2025-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Type - I', 'Type - I'), ('Type - II', 'Type - II'), ('Type - III', 'Type - III')], default='Type - I', max_length=20),
        ),
    ]
