# Generated by Django 5.2.5 on 2025-09-17 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('ai', models.BooleanField(default=False, help_text='Was this feature generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Todo', max_length=20)),
                ('role', models.CharField(help_text='Role responsible for this goal', max_length=50)),
                ('ai', models.BooleanField(default=False, help_text='Was this goal generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='Member role in the project', max_length=100)),
                ('ai', models.BooleanField(default=False, help_text='Was this member role suggested by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Project name', max_length=255)),
                ('summary', models.TextField(help_text='Project summary')),
                ('risks', models.TextField(blank=True, help_text='Project risks', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this project generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='PDF file of the proposal', upload_to='proposals/')),
                ('parsed_text', models.TextField(blank=True, help_text='Extracted content from PDF', null=True)),
                ('methodology', models.TextField(blank=True, help_text='Project methodology', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this proposal parsed by AI?')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
