# Generated by Django 5.2.5 on 2025-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_proposal_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='risks',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='methodology',
        ),
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.JSONField(default=list, help_text='List of roles associated with the project'),
        ),
    ]
