# Generated by Django 5.2.5 on 2025-09-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of roles associated with the project', null=True),
        ),
    ]
