# Generated by Django 5.2.5 on 2025-09-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='roles',
        ),
    ]
