# Generated by Django 5.2.5 on 2025-10-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_roles'),
        ('sprints', '0003_sprintgoal_delete_sprinttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_goals', to='sprints.sprint'),
        ),
    ]
