# Generated by Django 5.2.5 on 2025-10-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_goal_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
    ]
