# Generated by Django 5.2.5 on 2025-09-17 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Epic title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Epic description', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this epic generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='backlog.backlog')),
            ],
        ),
        migrations.CreateModel(
            name='SubEpic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Sub-Epic title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Sub-Epic description', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this sub-epic generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_epics', to='backlog.epic')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='User story title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='User story description', null=True)),
                ('acceptance_criteria', models.TextField(blank=True, help_text='Acceptance criteria', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this user story generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='backlog.subepic')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('ai', models.BooleanField(default=False, help_text='Was this task generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.goal')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backlog.userstory')),
            ],
        ),
    ]
