# Generated by Django 5.2.5 on 2025-09-17 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Sprint duration in days', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Sprint start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Sprint end date', null=True)),
                ('ai', models.BooleanField(default=False, help_text='Was this sprint generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
        ),
    ]
