# Generated by Django 5.2.5 on 2025-09-26 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='week_number',
            field=models.PositiveIntegerField(default=1, help_text='Week number in the project timeline'),
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task title for this sprint', max_length=255)),
                ('ai', models.BooleanField(default=False, help_text='Was this task generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sprints.sprint')),
            ],
        ),
    ]
