# Generated by Django 5.2.5 on 2025-10-01 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_sprint_week_number_sprinttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Goal title for this sprint', max_length=255)),
                ('ai', models.BooleanField(default=False, help_text='Was this goal generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='sprints.sprint')),
            ],
        ),
        migrations.DeleteModel(
            name='SprintTask',
        ),
    ]
